// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ExpandH
arma::mat ExpandH(int H, int d);
RcppExport SEXP _twmq_ExpandH(SEXP HSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(ExpandH(H, d));
    return rcpp_result_gen;
END_RCPP
}
// ExpandH_sample
arma::mat ExpandH_sample(int H, int d, int I);
RcppExport SEXP _twmq_ExpandH_sample(SEXP HSEXP, SEXP dSEXP, SEXP ISEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type I(ISEXP);
    rcpp_result_gen = Rcpp::wrap(ExpandH_sample(H, d, I));
    return rcpp_result_gen;
END_RCPP
}
// lossGaussMat
double lossGaussMat(const arma::mat& res, const double tau, const double h0, const double h1, const double h2);
RcppExport SEXP _twmq_lossGaussMat(SEXP resSEXP, SEXP tauSEXP, SEXP h0SEXP, SEXP h1SEXP, SEXP h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type res(resSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type h0(h0SEXP);
    Rcpp::traits::input_parameter< const double >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< const double >::type h2(h2SEXP);
    rcpp_result_gen = Rcpp::wrap(lossGaussMat(res, tau, h0, h1, h2));
    return rcpp_result_gen;
END_RCPP
}
// Loss_fun_mat
double Loss_fun_mat(const arma::mat& res, const double tau);
RcppExport SEXP _twmq_Loss_fun_mat(SEXP resSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type res(resSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(Loss_fun_mat(res, tau));
    return rcpp_result_gen;
END_RCPP
}
// Loss_fun_vec
double Loss_fun_vec(const arma::vec& res, const double tau);
RcppExport SEXP _twmq_Loss_fun_vec(SEXP resSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type res(resSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(Loss_fun_vec(res, tau));
    return rcpp_result_gen;
END_RCPP
}
// Loss_fun
double Loss_fun(NumericVector xvec, double tau);
RcppExport SEXP _twmq_Loss_fun(SEXP xvecSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xvec(xvecSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(Loss_fun(xvec, tau));
    return rcpp_result_gen;
END_RCPP
}
// Loss_memberG_mq
NumericMatrix Loss_memberG_mq(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_H, NumericVector taus);
RcppExport SEXP _twmq_Loss_memberG_mq(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_HSEXP, SEXP tausSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_H(member_HSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    rcpp_result_gen = Rcpp::wrap(Loss_memberG_mq(Ymat, W, X, theta_GH, member_H, taus));
    return rcpp_result_gen;
END_RCPP
}
// Loss_memberG_mq_conquer
NumericMatrix Loss_memberG_mq_conquer(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_H, NumericVector taus, const double h0, const double h1, const double h2);
RcppExport SEXP _twmq_Loss_memberG_mq_conquer(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_HSEXP, SEXP tausSEXP, SEXP h0SEXP, SEXP h1SEXP, SEXP h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_H(member_HSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< const double >::type h0(h0SEXP);
    Rcpp::traits::input_parameter< const double >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< const double >::type h2(h2SEXP);
    rcpp_result_gen = Rcpp::wrap(Loss_memberG_mq_conquer(Ymat, W, X, theta_GH, member_H, taus, h0, h1, h2));
    return rcpp_result_gen;
END_RCPP
}
// Loss_memberG_mq_additive
NumericMatrix Loss_memberG_mq_additive(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_H, NumericVector taus);
RcppExport SEXP _twmq_Loss_memberG_mq_additive(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_HSEXP, SEXP tausSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_H(member_HSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    rcpp_result_gen = Rcpp::wrap(Loss_memberG_mq_additive(Ymat, W, X, theta_GH, member_H, taus));
    return rcpp_result_gen;
END_RCPP
}
// Loss_memberG_mq_additive_conquer
NumericMatrix Loss_memberG_mq_additive_conquer(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_H, NumericVector taus, const double h0, const double h1, const double h2);
RcppExport SEXP _twmq_Loss_memberG_mq_additive_conquer(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_HSEXP, SEXP tausSEXP, SEXP h0SEXP, SEXP h1SEXP, SEXP h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_H(member_HSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< const double >::type h0(h0SEXP);
    Rcpp::traits::input_parameter< const double >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< const double >::type h2(h2SEXP);
    rcpp_result_gen = Rcpp::wrap(Loss_memberG_mq_additive_conquer(Ymat, W, X, theta_GH, member_H, taus, h0, h1, h2));
    return rcpp_result_gen;
END_RCPP
}
// Loss_memberG_mq_general
NumericMatrix Loss_memberG_mq_general(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_H, NumericVector taus);
RcppExport SEXP _twmq_Loss_memberG_mq_general(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_HSEXP, SEXP tausSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_H(member_HSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    rcpp_result_gen = Rcpp::wrap(Loss_memberG_mq_general(Ymat, W, X, theta_GH, member_H, taus));
    return rcpp_result_gen;
END_RCPP
}
// Loss_memberG_mq_general_conquer
NumericMatrix Loss_memberG_mq_general_conquer(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_H, NumericVector taus, const double h0, const double h1, const double h2);
RcppExport SEXP _twmq_Loss_memberG_mq_general_conquer(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_HSEXP, SEXP tausSEXP, SEXP h0SEXP, SEXP h1SEXP, SEXP h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_H(member_HSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< const double >::type h0(h0SEXP);
    Rcpp::traits::input_parameter< const double >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< const double >::type h2(h2SEXP);
    rcpp_result_gen = Rcpp::wrap(Loss_memberG_mq_general_conquer(Ymat, W, X, theta_GH, member_H, taus, h0, h1, h2));
    return rcpp_result_gen;
END_RCPP
}
// Update_memberH_mq
IntegerVector Update_memberH_mq(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, IntegerVector member_H_init, List FriendW, List FriendW2, NumericVector taus);
RcppExport SEXP _twmq_Update_memberH_mq(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP FriendW2SEXP, SEXP tausSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW2(FriendW2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_memberH_mq(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus));
    return rcpp_result_gen;
END_RCPP
}
// Update_memberH_mq_additive
IntegerVector Update_memberH_mq_additive(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, IntegerVector member_H_init, List FriendW, List FriendW2, NumericVector taus);
RcppExport SEXP _twmq_Update_memberH_mq_additive(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP FriendW2SEXP, SEXP tausSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW2(FriendW2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_memberH_mq_additive(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus));
    return rcpp_result_gen;
END_RCPP
}
// Update_memberH_mq_additive_conquer
IntegerVector Update_memberH_mq_additive_conquer(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, IntegerVector member_H_init, List FriendW, List FriendW2, NumericVector taus, const double h0, const double h1, const double h2);
RcppExport SEXP _twmq_Update_memberH_mq_additive_conquer(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP FriendW2SEXP, SEXP tausSEXP, SEXP h0SEXP, SEXP h1SEXP, SEXP h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW2(FriendW2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< const double >::type h0(h0SEXP);
    Rcpp::traits::input_parameter< const double >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< const double >::type h2(h2SEXP);
    rcpp_result_gen = Rcpp::wrap(Update_memberH_mq_additive_conquer(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus, h0, h1, h2));
    return rcpp_result_gen;
END_RCPP
}
// Update_memberH_mq_conquer
IntegerVector Update_memberH_mq_conquer(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, IntegerVector member_H_init, List FriendW, List FriendW2, NumericVector taus, const double h0, const double h1, const double h2);
RcppExport SEXP _twmq_Update_memberH_mq_conquer(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP FriendW2SEXP, SEXP tausSEXP, SEXP h0SEXP, SEXP h1SEXP, SEXP h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW2(FriendW2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< const double >::type h0(h0SEXP);
    Rcpp::traits::input_parameter< const double >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< const double >::type h2(h2SEXP);
    rcpp_result_gen = Rcpp::wrap(Update_memberH_mq_conquer(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus, h0, h1, h2));
    return rcpp_result_gen;
END_RCPP
}
// Update_memberH_mq_general
IntegerVector Update_memberH_mq_general(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, IntegerVector member_H_init, List FriendW, List FriendW2, NumericVector taus);
RcppExport SEXP _twmq_Update_memberH_mq_general(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP FriendW2SEXP, SEXP tausSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW2(FriendW2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_memberH_mq_general(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus));
    return rcpp_result_gen;
END_RCPP
}
// Update_memberH_mq_general_conquer
IntegerVector Update_memberH_mq_general_conquer(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, IntegerVector member_H_init, List FriendW, List FriendW2, NumericVector taus, const double h0, const double h1, const double h2);
RcppExport SEXP _twmq_Update_memberH_mq_general_conquer(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP FriendW2SEXP, SEXP tausSEXP, SEXP h0SEXP, SEXP h1SEXP, SEXP h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW2(FriendW2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< const double >::type h0(h0SEXP);
    Rcpp::traits::input_parameter< const double >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< const double >::type h2(h2SEXP);
    rcpp_result_gen = Rcpp::wrap(Update_memberH_mq_general_conquer(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus, h0, h1, h2));
    return rcpp_result_gen;
END_RCPP
}
// Proposal_memberH_mq
NumericMatrix Proposal_memberH_mq(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, arma::vec& member_H_init, List FriendW, arma::uvec& idx_update, NumericVector taus, int nsample);
RcppExport SEXP _twmq_Proposal_memberH_mq(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP idx_updateSEXP, SEXP tausSEXP, SEXP nsampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type idx_update(idx_updateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    rcpp_result_gen = Rcpp::wrap(Proposal_memberH_mq(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample));
    return rcpp_result_gen;
END_RCPP
}
// Proposal_memberH_mq_additive
NumericMatrix Proposal_memberH_mq_additive(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, arma::vec& member_H_init, List FriendW, arma::uvec& idx_update, NumericVector taus, int nsample);
RcppExport SEXP _twmq_Proposal_memberH_mq_additive(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP idx_updateSEXP, SEXP tausSEXP, SEXP nsampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type idx_update(idx_updateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    rcpp_result_gen = Rcpp::wrap(Proposal_memberH_mq_additive(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample));
    return rcpp_result_gen;
END_RCPP
}
// Proposal_memberH_mq_conquer
NumericMatrix Proposal_memberH_mq_conquer(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, arma::vec& member_H_init, List FriendW, arma::uvec& idx_update, NumericVector taus, int nsample, const double h0, const double h1, const double h2);
RcppExport SEXP _twmq_Proposal_memberH_mq_conquer(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP idx_updateSEXP, SEXP tausSEXP, SEXP nsampleSEXP, SEXP h0SEXP, SEXP h1SEXP, SEXP h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type idx_update(idx_updateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    Rcpp::traits::input_parameter< const double >::type h0(h0SEXP);
    Rcpp::traits::input_parameter< const double >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< const double >::type h2(h2SEXP);
    rcpp_result_gen = Rcpp::wrap(Proposal_memberH_mq_conquer(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample, h0, h1, h2));
    return rcpp_result_gen;
END_RCPP
}
// Proposal_memberH_mq_additive_conquer
NumericMatrix Proposal_memberH_mq_additive_conquer(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, arma::vec& member_H_init, List FriendW, arma::uvec& idx_update, NumericVector taus, int nsample, const double h0, const double h1, const double h2);
RcppExport SEXP _twmq_Proposal_memberH_mq_additive_conquer(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP idx_updateSEXP, SEXP tausSEXP, SEXP nsampleSEXP, SEXP h0SEXP, SEXP h1SEXP, SEXP h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type idx_update(idx_updateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    Rcpp::traits::input_parameter< const double >::type h0(h0SEXP);
    Rcpp::traits::input_parameter< const double >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< const double >::type h2(h2SEXP);
    rcpp_result_gen = Rcpp::wrap(Proposal_memberH_mq_additive_conquer(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample, h0, h1, h2));
    return rcpp_result_gen;
END_RCPP
}
// Proposal_memberH_mq_general_conquer
NumericMatrix Proposal_memberH_mq_general_conquer(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, arma::vec& member_H_init, List FriendW, arma::uvec& idx_update, NumericVector taus, int nsample, const double h0, const double h1, const double h2);
RcppExport SEXP _twmq_Proposal_memberH_mq_general_conquer(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP idx_updateSEXP, SEXP tausSEXP, SEXP nsampleSEXP, SEXP h0SEXP, SEXP h1SEXP, SEXP h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type idx_update(idx_updateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    Rcpp::traits::input_parameter< const double >::type h0(h0SEXP);
    Rcpp::traits::input_parameter< const double >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< const double >::type h2(h2SEXP);
    rcpp_result_gen = Rcpp::wrap(Proposal_memberH_mq_general_conquer(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample, h0, h1, h2));
    return rcpp_result_gen;
END_RCPP
}
// Proposal_memberH_mq_general
NumericMatrix Proposal_memberH_mq_general(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, arma::vec& member_H_init, List FriendW, arma::uvec& idx_update, NumericVector taus, int nsample);
RcppExport SEXP _twmq_Proposal_memberH_mq_general(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP idx_updateSEXP, SEXP tausSEXP, SEXP nsampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type idx_update(idx_updateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    rcpp_result_gen = Rcpp::wrap(Proposal_memberH_mq_general(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample));
    return rcpp_result_gen;
END_RCPP
}
// Refine_G_mq
NumericMatrix Refine_G_mq(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, arma::vec& member_H_init, List FriendW, NumericVector taus, int nsample);
RcppExport SEXP _twmq_Refine_G_mq(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP tausSEXP, SEXP nsampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    rcpp_result_gen = Rcpp::wrap(Refine_G_mq(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample));
    return rcpp_result_gen;
END_RCPP
}
// Refine_G_mq_conquer
NumericMatrix Refine_G_mq_conquer(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, arma::vec& member_H_init, List FriendW, NumericVector taus, int nsample, const double h0, const double h1, const double h2);
RcppExport SEXP _twmq_Refine_G_mq_conquer(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP tausSEXP, SEXP nsampleSEXP, SEXP h0SEXP, SEXP h1SEXP, SEXP h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    Rcpp::traits::input_parameter< const double >::type h0(h0SEXP);
    Rcpp::traits::input_parameter< const double >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< const double >::type h2(h2SEXP);
    rcpp_result_gen = Rcpp::wrap(Refine_G_mq_conquer(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample, h0, h1, h2));
    return rcpp_result_gen;
END_RCPP
}
// Refine_G_mq_additive
NumericMatrix Refine_G_mq_additive(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, arma::vec& member_H_init, List FriendW, NumericVector taus, int nsample);
RcppExport SEXP _twmq_Refine_G_mq_additive(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP tausSEXP, SEXP nsampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    rcpp_result_gen = Rcpp::wrap(Refine_G_mq_additive(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample));
    return rcpp_result_gen;
END_RCPP
}
// Refine_G_mq_additive_conquer
NumericMatrix Refine_G_mq_additive_conquer(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, arma::vec& member_H_init, List FriendW, NumericVector taus, int nsample, const double h0, const double h1, const double h2);
RcppExport SEXP _twmq_Refine_G_mq_additive_conquer(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP tausSEXP, SEXP nsampleSEXP, SEXP h0SEXP, SEXP h1SEXP, SEXP h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    Rcpp::traits::input_parameter< const double >::type h0(h0SEXP);
    Rcpp::traits::input_parameter< const double >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< const double >::type h2(h2SEXP);
    rcpp_result_gen = Rcpp::wrap(Refine_G_mq_additive_conquer(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample, h0, h1, h2));
    return rcpp_result_gen;
END_RCPP
}
// Refine_G_mq_general
NumericMatrix Refine_G_mq_general(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, arma::vec& member_H_init, List FriendW, NumericVector taus, int nsample);
RcppExport SEXP _twmq_Refine_G_mq_general(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP tausSEXP, SEXP nsampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    rcpp_result_gen = Rcpp::wrap(Refine_G_mq_general(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample));
    return rcpp_result_gen;
END_RCPP
}
// Refine_G_mq_general_conquer
NumericMatrix Refine_G_mq_general_conquer(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, arma::vec& member_H_init, List FriendW, NumericVector taus, int nsample, const double h0, const double h1, const double h2);
RcppExport SEXP _twmq_Refine_G_mq_general_conquer(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP tausSEXP, SEXP nsampleSEXP, SEXP h0SEXP, SEXP h1SEXP, SEXP h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    Rcpp::traits::input_parameter< const double >::type h0(h0SEXP);
    Rcpp::traits::input_parameter< const double >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< const double >::type h2(h2SEXP);
    rcpp_result_gen = Rcpp::wrap(Refine_G_mq_general_conquer(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample, h0, h1, h2));
    return rcpp_result_gen;
END_RCPP
}
// Refine_H_mq_general_conquer
NumericMatrix Refine_H_mq_general_conquer(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, arma::vec& member_H_init, List FriendW, List FriendW2, NumericVector taus, int nsample, const double h0, const double h1, const double h2);
RcppExport SEXP _twmq_Refine_H_mq_general_conquer(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP FriendW2SEXP, SEXP tausSEXP, SEXP nsampleSEXP, SEXP h0SEXP, SEXP h1SEXP, SEXP h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW2(FriendW2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    Rcpp::traits::input_parameter< const double >::type h0(h0SEXP);
    Rcpp::traits::input_parameter< const double >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< const double >::type h2(h2SEXP);
    rcpp_result_gen = Rcpp::wrap(Refine_H_mq_general_conquer(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus, nsample, h0, h1, h2));
    return rcpp_result_gen;
END_RCPP
}
// Refine_H_mq_general
NumericMatrix Refine_H_mq_general(const arma::mat& Ymat, const arma::mat& W, arma::cube X, List theta_GH, IntegerVector member_G, arma::vec& member_H_init, List FriendW, List FriendW2, NumericVector taus, int nsample);
RcppExport SEXP _twmq_Refine_H_mq_general(SEXP YmatSEXP, SEXP WSEXP, SEXP XSEXP, SEXP theta_GHSEXP, SEXP member_GSEXP, SEXP member_H_initSEXP, SEXP FriendWSEXP, SEXP FriendW2SEXP, SEXP tausSEXP, SEXP nsampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type theta_GH(theta_GHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type member_G(member_GSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type member_H_init(member_H_initSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW(FriendWSEXP);
    Rcpp::traits::input_parameter< List >::type FriendW2(FriendW2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    rcpp_result_gen = Rcpp::wrap(Refine_H_mq_general(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus, nsample));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_twmq_ExpandH", (DL_FUNC) &_twmq_ExpandH, 2},
    {"_twmq_ExpandH_sample", (DL_FUNC) &_twmq_ExpandH_sample, 3},
    {"_twmq_lossGaussMat", (DL_FUNC) &_twmq_lossGaussMat, 5},
    {"_twmq_Loss_fun_mat", (DL_FUNC) &_twmq_Loss_fun_mat, 2},
    {"_twmq_Loss_fun_vec", (DL_FUNC) &_twmq_Loss_fun_vec, 2},
    {"_twmq_Loss_fun", (DL_FUNC) &_twmq_Loss_fun, 2},
    {"_twmq_Loss_memberG_mq", (DL_FUNC) &_twmq_Loss_memberG_mq, 6},
    {"_twmq_Loss_memberG_mq_conquer", (DL_FUNC) &_twmq_Loss_memberG_mq_conquer, 9},
    {"_twmq_Loss_memberG_mq_additive", (DL_FUNC) &_twmq_Loss_memberG_mq_additive, 6},
    {"_twmq_Loss_memberG_mq_additive_conquer", (DL_FUNC) &_twmq_Loss_memberG_mq_additive_conquer, 9},
    {"_twmq_Loss_memberG_mq_general", (DL_FUNC) &_twmq_Loss_memberG_mq_general, 6},
    {"_twmq_Loss_memberG_mq_general_conquer", (DL_FUNC) &_twmq_Loss_memberG_mq_general_conquer, 9},
    {"_twmq_Update_memberH_mq", (DL_FUNC) &_twmq_Update_memberH_mq, 9},
    {"_twmq_Update_memberH_mq_additive", (DL_FUNC) &_twmq_Update_memberH_mq_additive, 9},
    {"_twmq_Update_memberH_mq_additive_conquer", (DL_FUNC) &_twmq_Update_memberH_mq_additive_conquer, 12},
    {"_twmq_Update_memberH_mq_conquer", (DL_FUNC) &_twmq_Update_memberH_mq_conquer, 12},
    {"_twmq_Update_memberH_mq_general", (DL_FUNC) &_twmq_Update_memberH_mq_general, 9},
    {"_twmq_Update_memberH_mq_general_conquer", (DL_FUNC) &_twmq_Update_memberH_mq_general_conquer, 12},
    {"_twmq_Proposal_memberH_mq", (DL_FUNC) &_twmq_Proposal_memberH_mq, 10},
    {"_twmq_Proposal_memberH_mq_additive", (DL_FUNC) &_twmq_Proposal_memberH_mq_additive, 10},
    {"_twmq_Proposal_memberH_mq_conquer", (DL_FUNC) &_twmq_Proposal_memberH_mq_conquer, 13},
    {"_twmq_Proposal_memberH_mq_additive_conquer", (DL_FUNC) &_twmq_Proposal_memberH_mq_additive_conquer, 13},
    {"_twmq_Proposal_memberH_mq_general_conquer", (DL_FUNC) &_twmq_Proposal_memberH_mq_general_conquer, 13},
    {"_twmq_Proposal_memberH_mq_general", (DL_FUNC) &_twmq_Proposal_memberH_mq_general, 10},
    {"_twmq_Refine_G_mq", (DL_FUNC) &_twmq_Refine_G_mq, 9},
    {"_twmq_Refine_G_mq_conquer", (DL_FUNC) &_twmq_Refine_G_mq_conquer, 12},
    {"_twmq_Refine_G_mq_additive", (DL_FUNC) &_twmq_Refine_G_mq_additive, 9},
    {"_twmq_Refine_G_mq_additive_conquer", (DL_FUNC) &_twmq_Refine_G_mq_additive_conquer, 12},
    {"_twmq_Refine_G_mq_general", (DL_FUNC) &_twmq_Refine_G_mq_general, 9},
    {"_twmq_Refine_G_mq_general_conquer", (DL_FUNC) &_twmq_Refine_G_mq_general_conquer, 12},
    {"_twmq_Refine_H_mq_general_conquer", (DL_FUNC) &_twmq_Refine_H_mq_general_conquer, 13},
    {"_twmq_Refine_H_mq_general", (DL_FUNC) &_twmq_Refine_H_mq_general, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_twmq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
