# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ExpandH <- function(H, d) {
    .Call(`_twmq_ExpandH`, H, d)
}

ExpandH_sample <- function(H, d, I) {
    .Call(`_twmq_ExpandH_sample`, H, d, I)
}

lossGaussMat <- function(res, tau, h0, h1, h2) {
    .Call(`_twmq_lossGaussMat`, res, tau, h0, h1, h2)
}

Loss_fun_mat <- function(res, tau) {
    .Call(`_twmq_Loss_fun_mat`, res, tau)
}

Loss_fun_vec <- function(res, tau) {
    .Call(`_twmq_Loss_fun_vec`, res, tau)
}

Loss_fun <- function(xvec, tau) {
    .Call(`_twmq_Loss_fun`, xvec, tau)
}

Loss_memberG_mq <- function(Ymat, W, X, theta_GH, member_H, taus) {
    .Call(`_twmq_Loss_memberG_mq`, Ymat, W, X, theta_GH, member_H, taus)
}

Loss_memberG_mq_conquer <- function(Ymat, W, X, theta_GH, member_H, taus, h0, h1, h2) {
    .Call(`_twmq_Loss_memberG_mq_conquer`, Ymat, W, X, theta_GH, member_H, taus, h0, h1, h2)
}

Loss_memberG_mq_additive <- function(Ymat, W, X, theta_GH, member_H, taus) {
    .Call(`_twmq_Loss_memberG_mq_additive`, Ymat, W, X, theta_GH, member_H, taus)
}

Loss_memberG_mq_additive_conquer <- function(Ymat, W, X, theta_GH, member_H, taus, h0, h1, h2) {
    .Call(`_twmq_Loss_memberG_mq_additive_conquer`, Ymat, W, X, theta_GH, member_H, taus, h0, h1, h2)
}

Loss_memberG_mq_general <- function(Ymat, W, X, theta_GH, member_H, taus) {
    .Call(`_twmq_Loss_memberG_mq_general`, Ymat, W, X, theta_GH, member_H, taus)
}

Loss_memberG_mq_general_conquer <- function(Ymat, W, X, theta_GH, member_H, taus, h0, h1, h2) {
    .Call(`_twmq_Loss_memberG_mq_general_conquer`, Ymat, W, X, theta_GH, member_H, taus, h0, h1, h2)
}

Update_memberH_mq <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus) {
    .Call(`_twmq_Update_memberH_mq`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus)
}

Update_memberH_mq_additive <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus) {
    .Call(`_twmq_Update_memberH_mq_additive`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus)
}

Update_memberH_mq_additive_conquer <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus, h0, h1, h2) {
    .Call(`_twmq_Update_memberH_mq_additive_conquer`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus, h0, h1, h2)
}

Update_memberH_mq_conquer <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus, h0, h1, h2) {
    .Call(`_twmq_Update_memberH_mq_conquer`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus, h0, h1, h2)
}

Update_memberH_mq_general <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus) {
    .Call(`_twmq_Update_memberH_mq_general`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus)
}

Update_memberH_mq_general_conquer <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus, h0, h1, h2) {
    .Call(`_twmq_Update_memberH_mq_general_conquer`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus, h0, h1, h2)
}

Proposal_memberH_mq <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample) {
    .Call(`_twmq_Proposal_memberH_mq`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample)
}

Proposal_memberH_mq_additive <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample) {
    .Call(`_twmq_Proposal_memberH_mq_additive`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample)
}

Proposal_memberH_mq_conquer <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample, h0, h1, h2) {
    .Call(`_twmq_Proposal_memberH_mq_conquer`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample, h0, h1, h2)
}

Proposal_memberH_mq_additive_conquer <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample, h0, h1, h2) {
    .Call(`_twmq_Proposal_memberH_mq_additive_conquer`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample, h0, h1, h2)
}

Proposal_memberH_mq_general_conquer <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample, h0, h1, h2) {
    .Call(`_twmq_Proposal_memberH_mq_general_conquer`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample, h0, h1, h2)
}

Proposal_memberH_mq_general <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample) {
    .Call(`_twmq_Proposal_memberH_mq_general`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, idx_update, taus, nsample)
}

Refine_G_mq <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample) {
    .Call(`_twmq_Refine_G_mq`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample)
}

Refine_G_mq_conquer <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample, h0, h1, h2) {
    .Call(`_twmq_Refine_G_mq_conquer`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample, h0, h1, h2)
}

Refine_G_mq_additive <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample) {
    .Call(`_twmq_Refine_G_mq_additive`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample)
}

Refine_G_mq_additive_conquer <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample, h0, h1, h2) {
    .Call(`_twmq_Refine_G_mq_additive_conquer`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample, h0, h1, h2)
}

Refine_G_mq_general <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample) {
    .Call(`_twmq_Refine_G_mq_general`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample)
}

Refine_G_mq_general_conquer <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample, h0, h1, h2) {
    .Call(`_twmq_Refine_G_mq_general_conquer`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, taus, nsample, h0, h1, h2)
}

Refine_H_mq_general_conquer <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus, nsample, h0, h1, h2) {
    .Call(`_twmq_Refine_H_mq_general_conquer`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus, nsample, h0, h1, h2)
}

Refine_H_mq_general <- function(Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus, nsample) {
    .Call(`_twmq_Refine_H_mq_general`, Ymat, W, X, theta_GH, member_G, member_H_init, FriendW, FriendW2, taus, nsample)
}

